GRAPH, G = (V , E)

V is a set of vertices or nodes. E is a set of edges. E proper subset of V.

A path is a sequence of vertices v1,v2,...vk connected by edges.

Reachability : A vertex v is reachable from vertex u if there is a path from u to v.

Representation:

Adjacency matrix : Rows and columns numbred {0,1,2,...,n-1}

A[i,j] = 1 if there exists and edge between vertices (i,j).

In [3]:
# For example,

import numpy as np

edges = [(0,1), (0,4), (3,4), (7,2), (8,5)]
A = np.zeros(shape = (10,10))

for (i,j) in edges:
    A[i,j] = 1

print(A)

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


If it's an undirected graph then, A[i,j] = A[j,i] = 1. [Symmetric across main diagonal]

In [5]:
edges = [(0,1), (0,4), (3,4), (7,2), (8,5)]
A = np.zeros(shape = (10,10))

for (i,j) in edges:
    A[i,j] = 1
    A[j,i] = 1

print(A)

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
 # Identifying neighbors of a row.

def neighbors(AMat,i):
    nbrs = []
    (row,cols) = AMat.shape
    for j in range(cols):
        if AMat[i,j] == 1:
            nbrs.append(j)
    return nbrs

print(neighbors(A,5))

[8]


In case of a directed graph, the rows represent outgoing edges and the columns represent incoming edges.

For example, A[3,5] == 1 signifies an edge from 3 to 5.

Degree of a vertex i = Number of edges incident on i.

In order to check reachability, first we mark the source vertex ie. our starting point as reachable. Systematically mark neighbors of marked vertices. We stop when target becomes marked.

For this, we need a strategy to systematically explore marked neighbors.

Better representation for the adjacency matrix is the list of neighbors for each vertex, since the adjacency matrix is quite sparse and typically takes more space than the said list.

In [11]:
# Example of an adjacency list.

edges = [(0,1), (7,6),(0,4), (3,4), (7,2), (8,5)]
adj_list = {}

for i in range(10):
    adj_list[i] = []
for (i,j) in edges:
    adj_list[i].append(j)

print(adj_list)

{0: [1, 4], 1: [], 2: [], 3: [4], 4: [], 5: [], 6: [], 7: [6, 2], 8: [5], 9: []}


BREADTH FIRST SEARCH (BFS)

Explore the graph level by level -->> First vist vertices that are one step away, then the ones that are two step away and so on.

Each visited vertex has to be explored -->> extend the search to its neighbors (only once for each vertex).

Maintaining information about vertices -->> Like, which vertices have been visited already, and among these visited ones which among them are yet to be explored.

V = {0,1,...,n-1}

visited (dictionary) -->> True if visited else False. Initally, visited(v) = False.

maintaining a sequence of visited vertices yet to be explored -->> use a queue ( first in first out ).

exploring a vertex i -->> For each edge (i,j), if visited(j) is False, then set visited(j) as True and append j to the queue.

Dry Run ::

Initially, visited(v) == False for all vertices. Queue of vertices to be explored is empty as well.

Start BFS from vertex j. -->> Set visited[j] as True and add j to the queue.

Remove and explore vertex i at head of the queue. -->> For each edge (i,j), if visited(j) if False,
set visited(j) to True and append j to the queue.

So, for vertex j we will check it's corresponding connected vertices. We will choose one of its corresposnidng vertices and then remove from the queue and so on. 

In [14]:
class Queue:
    def __init__(self):
        self.queue = []
    def addq(self,v):
        self.queue.append(v)
    def delq(self):
        v=None
        if not self.isempty():
            v=self.queue[0]
            self.queue = self.queue[1:]
        return v
    def isempty(self):
        return (self.queue==[])
    def __str__(self):
        return str(self.queue)

In [16]:
def BFS(AMat,v):
    (rows,cols) = AMat.shape
    visited = {}
    for i in range(rows):
        visited[i]=False
    q=Queue()

    visited[v]=True
    q.addq(v)

    while (not q.isempty()):
        j = q.delq()
        for k in neighbors(AMat, j):
            if not visited[k]:
                visited[k] = True
                q.addq(k)

    return visited

Complexity of BFS:

Let G, a connected graph have n vertices and m edges. m can vary from (n-1) to n(n-1)/2 edges. 

In BFS, each reachable vertex is processed exactly once. 

Exploring a particular vertex includes scanning all its neighbors.

Using an adjacency matrix takes O(n2) since it takes n steps to initialize each vertex and n steps to explore each vertex. Using an adjacency list however, takes same n steps to intialize each vertex but 2m(degrees of freedom) steps to explore all vertices. Overall time reducing to O(m+n).



Enhancing BFS to record paths:

In [17]:
def BFS_lispath(Alist,v):
    visited,parent = {},{}
    for i in Alist.keys():
        visited[i]=False
        parent[i]=-1
    q=Queue()

    visited[v]=True
    q.addq(v)

    while not q.isempty():
        j=q.delq()
        for k in Alist[j]:
            if not visited[k]:
                visited[k]=True
                parent[k]=j
                q.addq(k)
    
    return visited,parent

Enhancing BFS to record paths:

In [18]:
def BFS_listdist(Alist,v):
    level,parent = {},{}
    for i in Alist.keys():
        level[i]=-1
        parent[i]-1
    q=Queue()

    level[v]=0
    q.addq(v)

    while not q.isempty():
        j=q.delq()
        for k in Alist[j]:
            if level[k] == -1:
                level[k] = level[j] + 1
                parent[k] = j
                q.addq(k)
    return level,parent

DEPTH FIRST SEARCH:

Start from vertex i, visit an unexplored neighbour j. 

Suspend the exploration of i and explore j instead.

Continue till you reach a vertex with no unexplored neighbours.

Backtrack to nearest suspended vertex that still has an unexplores neighbour.

Suspended vertices are stored in a stack (first in last out) (Most recently suspended is checked first).